sudo: required
services:
  - docker

before_install:
  - docker build -t sglavatchi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sglavatchi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-543633097370"
  bucket_path: "docker-react"
  on: 
   branch: master
  access_key_id:
    secure: "$aws_access_key"
  secret_access_key:
    secure: "$aws_secret_key"
