sudo: required
services:
  - docker

before_install:
  - docker build -t sglavatchi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sglavatchi/docker-react npm run test -- --coverage
